name: Deployment Workflow
on:
  push:
    branches:
      - master

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: "Greetings"
        run: |
          echo "--- Greetings ----"
      
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Create version number"
        run: |
          echo "APP_VERSION=${RANDOM}" >> $GITHUB_ENV

          echo ${{ env.APP_VERSION }}

      - name: checks out the repository
        uses: actions/checkout@v3
                     

      - name: "Logs into docker"
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}  
      
      - name: "Build the image"
        run: |
          echo ${{ env.APP_VERSION }}
          sudo docker build -t seun007/booksiread:${{ env.APP_VERSION }} frontend/
      - name: "Push the image to docker hub" 
        run: |
            docker push seun007/booksiread:${{ env.APP_VERSION }}

      # - name: "Annouce the latest version of the deployment"
      #   uses: dawidd6/action-send-mail@v4
      #   with:
      #     username: sadiboseun@yahoo.com
      #     password: ${{ secrets.EMAIL_PASSWORD }}
      #     server_address: smtp.mail.yahoo.com
      #     server_port: 465
      #     secure: true
      #     subject: "New Docker Image Version for Simple Web App"
      #     from: Sadibo Seun <sadiboseun@yahoo.com>
      #     to: "sadiboseun2013@gmail.com"
      #     body: "New image build: ${{ env.APP_VERSION }}"      